import type { ChecklistItem, FormField } from '../data/visaRequirements'
import type { TripInfo } from '../types'

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function buildCaseSummaryHtml(params: {
  trip: TripInfo
  baseFields: FormField[]
  checklist: ChecklistItem[]
  formAnswers: Record<string, string>
  checklistState: Record<string, boolean>
  signature: string | null
}): string {
  const { trip, baseFields, checklist, formAnswers, checklistState, signature } = params

  const fieldRows = (fields: FormField[]) =>
    fields
      .map(
        (f) =>
          `<tr><td>${escapeHtml(f.label)}</td><td>${escapeHtml(formAnswers[f.id] ?? '—')}</td></tr>`,
      )
      .join('')

  const checklistRows = checklist
    .map((item) => {
      const done = checklistState[item.id]
      return `
        <li>
          <strong>${done ? '✓' : '☐'} ${escapeHtml(item.label)}</strong>
          <p>${escapeHtml(item.instructions)}</p>
          ${item.fields.length ? `<table>${fieldRows(item.fields)}</table>` : ''}
        </li>`
    })
    .join('')

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>NestGo case — ${escapeHtml(trip.destinationCity)}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 720px; margin: 40px auto; color: #111; }
  h1 { font-size: 22px; }
  table { border-collapse: collapse; margin: 8px 0 16px; }
  td { padding: 4px 12px 4px 0; border-bottom: 1px solid #eee; }
  li { margin-bottom: 20px; list-style: none; }
  ul { padding: 0; }
  img { max-height: 80px; border: 1px solid #ddd; margin-top: 8px; }
</style>
</head>
<body>
  <h1>NestGo case summary</h1>
  <p>${escapeHtml(trip.originCity)}, ${escapeHtml(trip.originCountry)} → ${escapeHtml(
    trip.destinationCity,
  )}, ${escapeHtml(trip.destinationCountry)} — ${escapeHtml(trip.purpose)}</p>

  <h2>Identity details</h2>
  <table>${fieldRows(baseFields)}</table>

  <h2>Checklist</h2>
  <ul>${checklistRows}</ul>

  <h2>Signature</h2>
  ${signature ? `<img src="${signature}" alt="signature">` : '<p>Not yet captured.</p>'}

  <p style="margin-top:32px;color:#888;font-size:12px;">
    Generated by NestGo. This is a starter summary, not an official government
    document — confirm every requirement with the destination country's
    official immigration portal before relying on it.
  </p>
</body>
</html>`
}
