import { useState } from 'react'
import type { ChecklistItem } from '../data/visaRequirements'
import { buildGoogleCalendarUrl } from '../lib/calendar'
import { buildProcedureSearchUrl } from '../lib/officialLinks'
import { useTrip } from '../lib/tripState'

export function ChecklistItemRow({ item }: { item: ChecklistItem }) {
  const { state, setFormAnswer, toggleChecklistItem, logActivity } = useTrip()
  const trip = state.trip!
  const [expanded, setExpanded] = useState(false)
  const done = !!state.checklist[item.id]

  const calendarUrl = buildGoogleCalendarUrl(
    `NestGo: ${item.label}`,
    `${item.instructions}\n\nGenerated by NestGo for your ${trip.purpose} move to ${trip.destinationCity}, ${trip.destinationCountry}.`,
  )
  const officialUrl = buildProcedureSearchUrl(
    trip.destinationCountry,
    trip.destinationCity,
    item.label,
    item.online,
  )

  return (
    <li className="rounded-lg border border-slate-200 dark:border-slate-800">
      <div className="flex items-center gap-3 px-4 py-3 text-sm">
        <button
          type="button"
          onClick={() => toggleChecklistItem(item.id, item.label)}
          className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full border text-xs ${
            done
              ? 'border-emerald-700 bg-emerald-700 text-white'
              : 'border-slate-300 dark:border-slate-600'
          }`}
        >
          {done ? '✓' : ''}
        </button>
        <button
          type="button"
          onClick={() => setExpanded((e) => !e)}
          className={`flex-1 text-left ${done ? 'text-slate-400 line-through' : ''}`}
        >
          {item.label}
        </button>
        <a
          href={calendarUrl}
          target="_blank"
          rel="noreferrer"
          onClick={() => logActivity(`Set Google Calendar reminder: ${item.label}`)}
          className="shrink-0 rounded-md border border-slate-300 px-2 py-1 text-xs text-slate-600 hover:border-emerald-600 hover:text-emerald-700 dark:border-slate-700 dark:text-slate-300"
        >
          📅
        </a>
        <button
          type="button"
          onClick={() => setExpanded((e) => !e)}
          className="shrink-0 text-xs text-slate-400"
        >
          {expanded ? '▲' : '▼'}
        </button>
      </div>

      {expanded && (
        <div className="border-t border-slate-100 px-4 py-3 text-sm dark:border-slate-800">
          <p className="text-slate-600 dark:text-slate-300">{item.instructions}</p>

          {item.fields.length > 0 && (
            <div className="mt-3 grid gap-3 sm:grid-cols-2">
              {item.fields.map((field) => (
                <div key={field.id}>
                  <label className="text-xs font-medium text-slate-500 dark:text-slate-400">
                    {field.label}
                  </label>
                  <input
                    type={field.type}
                    value={state.formAnswers[field.id] ?? ''}
                    onChange={(e) => setFormAnswer(field.id, e.target.value)}
                    onBlur={() => logActivity(`Filled in: ${field.label} (${item.label})`)}
                    className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950"
                  />
                </div>
              ))}
            </div>
          )}

          <div className="mt-3 flex items-center justify-between">
            <a
              href={officialUrl}
              target="_blank"
              rel="noreferrer"
              onClick={() => logActivity(`Looked up official source for: ${item.label}`)}
              className="inline-block text-xs font-medium text-emerald-700 hover:underline dark:text-emerald-400"
            >
              {item.online
                ? '🔎 Find the official online form/portal'
                : '🔎 Find the nearest office'}
            </a>
            {item.lastVerifiedAt && (
              <span className="text-xs text-slate-400">Verified {item.lastVerifiedAt}</span>
            )}
          </div>
        </div>
      )}
    </li>
  )
}
